### ISSUE TITLE
Piechart Donut not working when switching to transparent mode

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [grafana/piechart-panel#45]
The Pie chart won't display as a donut when switching the panel to transparent mode. It will switch to a pie and can't be switched back unless transparent mode is turned off.

**Comment by gretamosa** [comment]
This is an issue that I have fixed in PR #44 with some other improvements.

**Comment by pn-d9t** [comment]
@gretamosa I have applied the changes from PR #44 but donuts are still not working in transparent mode.

**Comment by gretamosa** [comment]
@pn-d9t do you have applied all changes? I attach you the snapshot of the change that solve this issue:

![snap2](https://cloud.githubusercontent.com/assets/16796053/17963578/83f25544-6ab6-11e6-9b77-6ae6219f0230.png)

**Comment by pn-d9t** [comment]
Thanks for your fast reply, when I apply #44 and restart grafana all my pie and donut charts have a white background. I tried to adjust the values from 255,255,255 to 20,20,20 but no visible change: 
![screenshot from 2016-08-25 11-47-38](https://cloud.githubusercontent.com/assets/19552526/17964513/e080e2c8-6ab9-11e6-87fe-1b395b3772af.png)
![screenshot from 2016-08-25 11-46-56](https://cloud.githubusercontent.com/assets/19552526/17964514/e09c760a-6ab9-11e6-8fdc-677798a5d436.png)

**Comment by gretamosa** [comment]
@pn-d9t do you re-compile the plugin (grunt command) after the change? this is the result after rgb(20,20,20) modification and re-compile plugin.

![snap3](https://cloud.githubusercontent.com/assets/16796053/17965504/4387ceb0-6abd-11e6-99d7-b11a8c220b74.png)

**Comment by gretamosa** [comment]
@pn-d9t Plugin compilation needs more steps. Just run "grunt" into the piechart plugin directory (i.e. verify & copy all necessary fields into dist folder) and that's all. 

Another option is edit rendering.js file from dist directory (not recommended if you're going to make more changes over the plugin).

**Comment by pn-d9t** [comment]
@gretamosa After fiddling around with npm install and grunt I got it working now. But there is a new problem now: "Direct link rendered image" from the share panel are empty now. How can I fix this?

**Comment by gretamosa** [comment]
@pn-d9t Could you verify if "Direct link rendered image" works with other graphs? I am not pretty sure if its a plugin bug or it depends grafana code (attach logs if necessary).

**Comment by Ijin08** [comment]
This is fixed with pr #96.
